version: 2
jobs:
  build-test:
    macos:
      xcode: "10.1.0"
    environment:
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
      MATCH_KEYCHAIN_NAME: "circle"
      MATCH_KEYCHAIN_PASSWORD: "circle"
    steps:
      - checkout
      - run:
          name: Installing Gems
          command: |
            sudo gem install fastlane
            sudo gem install cocoapods -v 1.5.3
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: cd ~/project; pod install --verbose
      - run:
          name: POEditor Strings Upload/Download
          command: |
            fastlane poeditor_upload
            fastlane poeditor_download
      - run:
          name: Build and run tests
          command: fastlane scan --scheme "nextgen"
      - store_test_results:
          path: ~/project/fastlane/test_output/report.html
      - store_artifacts:
          path: ~/project/fastlane/Fastfile
      - run:
          name: Code signing setup
          command: |
            cd ~/project
            fastlane create_temporary_keychain
            fastlane match appstore --readonly
      - run:
          name: Beta Distribution
          no_output_timeout: 30m
          command: |
            cd ~/project/
            fastlane beta
      - store_artifacts:
          path: ~/project/nextgen.ipa
          destination: nextgen.ipa
      - store_artifacts:
          path: ~/project/nextgen.app.dSYM.zip
          destination: dSYM.zip

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-test:
          filters:
            branches:
              only: 
                - master
                - wang-ft-firmware
